version: 2  
updates:  
  # Configuração para dependências Ruby (Gemfile)  
  - package-ecosystem: "rubygems"  
    directory: "/"  # Diretório onde está o Gemfile  
    schedule:  
      interval: "weekly"  # Verificações semanais  
    commit-message:  
      prefix: "fix"  # Prefixo na mensagem de commit  
      include: "scope"  # Inclui o nome da dependência na mensagem  

  # Configuração para dependências JavaScript (package.json)  
  - package-ecosystem: "npm"  
    directory: "/"  # Diretório onde está o package.json  
    schedule:  
      interval: "weekly"  # Verificações semanais  
    commit-message:  
      prefix: "fix"  # Prefixo na mensagem de commit  
      include: "scope"  # Inclui o nome da dependência na mensagem  
    versioning-strategy: "auto"  # Estratégia de versão
