
                   💖 Sponsored

                < with love & joy /> ❦



☆☆☆ github: [ @FabianaCampanari, @Quantum-Software-Development ]
github: [ 'https://github.com/FabianaCampanari', 'https://github.com/Quantum-Software-Development' ]


stripre_express: @FabianaCampanari  
stripre_express: ['https://stripe.com/docs/financial-services']


open_collective: [ @FabianaCampanari. @quantum-software-development ]
open_collective: [ 'https://opencollective.com/fabianacampanari', 'https://opencollective.com/quantum-software-development' ]


✩☆☆☆Embed Sponsor button
<iframe src="https://github.com/sponsors/FabianaCampanari/button" title="Sponsor FabianaCampanari" height="32" width="114" style="border: 0; border-radius: 6px;"></iframe>


Embed a Sponsor card
<iframe src="https://github.com/sponsors/FabianaCampanari/card" title="Sponsor FabianaCampanari" height="225" width="600" style="border: 0;"></iframe>





















🧘🏼‍♀️ Sponsored Profile

gitHub: @FabianaCampanari
['https://github.com/FabianaCampanari']

####

💰 Sponsored Profile Github Bank Account

stripre_express: @FabianaCampanari
['https://stripe.com/docs/financial-services']

####

💼  Spomsored Ptofile Fiscal Host: 

open_collective: @FabianaCampanari
['https://opencollective.com/fabianacampanari',
'https://opencollective.com/fabianacampanari/projects/average-calculator']


