
                   💖 Sponsored

                < with love & joy /> ❦



github:  @FabianaCampanari, @Quantum-Software-Development]

github: ['https://github.com/FabianaCampanari', 'https://github.com/Quantum-Software-Development']
, @Quantum-Software-Development]




open_collective: [@fabiana-campanari , @quantum-software-development]











🧘🏼‍♀️ Sponsored Profile

gitHub: @FabianaCampanari
['https://github.com/FabianaCampanari']

####

💰 Sponsored Profile Github Bank Account

stripre_express: @FabianaCampanari
['https://stripe.com/docs/financial-services']

####

💼  Spomsored Ptofile Fiscal Host: 

open_collective: @FabianaCampanari
['https://opencollective.com/fabianacampanari',
'https://opencollective.com/fabianacampanari/projects/average-calculator']


